name: FORK-01 Automated check-only SalesForce deployment to CODEMERGE org
on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    
    branches:
      - develop
    
    paths:
      - 'force-app/**'

permissions:
  contents: read # for checkout
  pull-requests: write # for commenting
  issues: write # for commenting
  actions: write # for upload of code scanning results
  security-events: write
  
jobs:   
  add-label:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[Dummy]') && github.event.repository.fork }}
    steps:
      - name: Add label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: ['do-not-merge']
            });
  check-only-deployment-on-org:
    needs: add-label
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to CODEMERGE org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ secrets.SFDX_CODEMERGE_URL }}
      - name: Perform a check-only deployment to CODEMERGE Org
        uses: ./.github/actions/salesforce_verification_deploy
        with:
          head_branch_name: ${{ github.event.pull_request.head.sha }}
          diff_branch_name: ${{ github.event.pull_request.base.sha }}
          username: ${{ secrets.CODEMERGE_ORG_USERNAME }}
  comment:
    runs-on: ubuntu-latest
    needs: check-only-deployment-on-org
    if: success()
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `
              ✅ Check-only deployment to CODEMERGE succeeded!

              Once all tests/checks have been completed, trigger the deployment to QA by creating a new comment on this PR, with message:
                /deploy-to-qa
              `
            });
