name: FORK-04 Automatically notify users when changes are pushed to main
on: 
  push:
    branches: 
      - main
jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}
    steps:
        - name: Create issue and assign user
          uses: actions/github-script@v7
          env:
            ASSIGNEES: ${{ vars.MAIN_APPROVERS }}
          with:
            github-token: ${{ secrets.FORK_PAT }}
            script: |
                const ownerx = `${context.repo.owner}`;
                const repox = `${context.repo.repo}`;
                const assigneesString = process.env.ASSIGNEES;
                const assignees = assigneesString.split(',').map(a => a.trim());
                console.log("Creating issue and assigning it to:");
                console.log(assignees);
                const title = `Push to main branch by ${context.actor}`;
                const body = `
                A push was made to the **main** branch.

                **Repository:** ${context.repo.owner}/${context.repo.repo}
                **Pushed by:** ${context.actor}
                **Commit SHA:** ${context.sha}

                You have been assigned to this notification to review the changes and cascade them into your development branch.
                `;

                await github.rest.issues.create({
                    owner: ownerx,
                    repo: repox,
                    title,
                    body,
                    assignees
                });
                console.log("Issue created");