name: MAIN-05 Manual SalesForce deployment to PreProd org
on: 
  workflow_call:
    inputs:
      pr_branch:
        required: true
        type: string
      pr_repo:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      pr_sha:
        required: true
        type: string
    secrets:
      SFDX_PREPROD_URL:
        required: true
      PREPROD_ORG_USERNAME:
        required: true
      INSTANCE_URL:
        required: true
      PROFILE_NAMES:
        required: true

permissions:
  contents: write # for checkout
  pull-requests: write # for commenting
  issues: write # for commenting
  actions: write # for upload of code scanning results
  
jobs: 
  check_previous_workflow_succeeded:
    runs-on: ubuntu-latest
    steps:
      - name: Check prior workflow status
        uses: actions/github-script@v7
        env:
          BRANCH_NAME: ${{ inputs.pr_branch }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branchName = process.env.BRANCH_NAME;
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: "03_main_manual_deploy_to_org.yml",
              branch: "release-backlog"
            });

            if (!branchName.startsWith("release/") && !branchName.startsWith("hotfix/")) {
              core.setFailed("Pipeline should only be run from a release candidate branch (release/[date]) or hotfix branch (hotfix/[...])")
            }

            if (!workflows.data.workflow_runs.length || workflows.data.workflow_runs[0].conclusion !== "success") {
              core.setFailed("Previous workflow did not succeed (deployment to UAT). Manual trigger denied.");
            }
  
  add-pending-comment:
    runs-on: ubuntu-latest
    needs: check_previous_workflow_succeeded
    if: success()
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        env:
          pr_number: ${{ inputs.pr_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.pr_number;
            const { owner, repo } = context.repo;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `
              ⏳ Deploying to PreProd org...
              `
            });

  deployment-on-PreProd-org:
    needs: check_previous_workflow_succeeded
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to PreProd org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ secrets.SFDX_PREPROD_URL }}
      - name: Get SHAs
        id: shas
        run: |
          FROM_SHA=$(git rev-parse origin/main^{commit})
          echo "from_sha=$FROM_SHA" >> $GITHUB_OUTPUT
      - name: Perform a deployment to QA Org
        uses: ./.github/actions/salesforce_deploy
        with:
          head_branch_name: ${{ inputs.pr_sha }}
          diff_branch_name: ${{ steps.shas.outputs.from_sha }}
          username: ${{ secrets.PREPROD_ORG_USERNAME }}

  comment-success:
    runs-on: ubuntu-latest
    needs: deployment-on-PreProd-org
    if: success()
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        env:
          pr_number: ${{ inputs.pr_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.pr_number;
            const { owner, repo } = context.repo;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `
              ✅ Deployment to PreProd succeeded!

              Update of field-level security now proceeding in the background.

              Once all tests/checks have been completed, trigger the deployment to Prod by creating a new comment on this PR, with message:
                /deploy-to-prod
              `
            });

  comment-failure:
    runs-on: ubuntu-latest
    needs: deployment-on-PreProd-org
    if: failure()
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v7
        env:
          pr_number: ${{ inputs.pr_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.pr_number;
            const { owner, repo } = context.repo;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `
              ❌ Deployment to PreProd failed.
              `
            });

  add-fls-to-org:
    needs: deployment-on-PreProd-org
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to PreProd org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ secrets.SFDX_PREPROD_URL }}
      - name: Apply FLS
        uses: ./.github/actions/salesforce_add_fls
        with:
          instance_url: ${{ secrets.INSTANCE_URL }}
          username: ${{ secrets.PREPROD_ORG_USERNAME }}
          profile_names: ${{ secrets.PROFILE_NAMES }}