name: ADHOC / SANDBOX deployment
description: Pipeline which can be used for ad-hoc deployments to standalone sandbox environments. A verification deployment is run first, followed by actual deployment and field-level security (if required)
on: 
  workflow_dispatch:
    inputs:
      sfdx_auth_url: 
        description: Salesforce Authentication URL for the org you wish to deploy to
        required: true
        type: string
      org_alias:
        description: The alias / username used for the org you wish to deploy to
        required: true
        type: string
      instance_url:
        description: URL that identifies the specific sever cluster your org is hosted on. E.g. for a sandbox this would be https://test.salesforce.com
        required: true
        type: string
      diff_branch_name:
        description: Branch to compare with to produce delta for deployment
        required: true
        type: string
  
jobs: 
  get-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
      to_sha: ${{ steps.shas.outputs.to_sha }}
      from_sha: ${{ steps.shas.outputs.from_sha }}
    steps:
      - name: Get branch name
        id: get_branch_name
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
      - name: Get SHAs
        id: shas
        run: |
          FROM_SHA=$(git rev-parse origin/${{ github.event.inputs.diff_branch_name }}^{commit})
          TO_SHA=$(git rev-parse origin/${{ steps.get_branch_name.outputs.BRANCH_NAME }}^{commit})
          echo "from_sha=$FROM_SHA" >> $GITHUB_OUTPUT
          echo "to_sha=$TO_SHA" >> $GITHUB_OUTPUT

  verification-testing-deployment:
    runs-on: ubuntu-latest
    needs: get-branch-name
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ github.event.inputs.sfdx_auth_url }}
      - name: Perform a deployment to Org
        uses: ./.github/actions/salesforce_deploy
        with:
          head_branch_name: ${{ needs.get-branch-name.outputs.to_sha }}
          diff_branch_name: ${{ needs.get-branch-name.outputs.from_sha }}
          username: ${{ github.event.inputs.org_alias }}

  deployment:
    needs: 
      - get-branch-name
      - verification-testing-deployment
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ github.event.inputs.sfdx_auth_url }}
      - name: Perform a deployment to org
        uses: ./.github/actions/salesforce_deploy
        with:
          head_branch_name: ${{ needs.get-branch-name.outputs.to_sha }}
          diff_branch_name: ${{ needs.get-branch-name.outputs.from_sha }}
          username: ${{ github.event.inputs.org_alias }}

  add-fls-to-org:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up the environment
        uses: ./.github/actions/salesforce_runner_env
      - name: Auth to org
        uses: ./.github/actions/salesforce_authorisation
        with:
          organisation_url: ${{ github.event.inputs.sfdx_auth_url }}
      - name: Apply FLS
        uses: ./.github/actions/salesforce_add_fls
        with:
          instance_url: ${{ github.event.inputs.instance_url }}
          username: ${{ github.event.inputs.org_alias }}
          profile_names: ${{ secrets.PROFILE_NAMES }}
          