name: MAIN-92 Router workflow for manual deployments
on: 
  issue_comment:
    types: [created]

jobs:
  get_pr_branch:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request != null && startsWith(github.event.comment.body, '/') }}
    outputs:
      pr_branch: ${{ steps.pr.outputs.pr_branch }}
      pr_repo: ${{ steps.pr.outputs.pr_repo }}
      pr_number: ${{ steps.pr.outputs.pr_number }}
      pr_sha: ${{ steps.pr.outputs.pr_sha }}
    steps:
      - name: Get PR head branch
        id: pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prUrl = context.payload.issue.pull_request.url;
            const pr = await github.request(prUrl);

            core.setOutput("pr_branch", pr.data.head.ref);
            core.setOutput("pr_repo", pr.data.head.repo.full_name);
            core.setOutput("pr_number", pr.data.number);
            core.setOutput("pr_sha", pr.data.head.sha);

  # Route to QA deployment
  route-to-qa:
    needs: get_pr_branch
    if: ${{ github.event.comment.body == '/deploy-to-qa' && !github.event.repository.fork }}
    uses: ./.github/workflows/04_main_manual_deploy_to_qa.yml
    secrets:
      SFDX_QA_URL: ${{ secrets.SFDX_QA_URL }}
      QA_ORG_USERNAME: ${{ secrets.QA_ORG_USERNAME }}
      INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
      PROFILE_NAMES: ${{ secrets.PROFILE_NAMES }}

  # Route to UAT deployment
  route-to-uat:
    needs: get_pr_branch
    if: ${{ github.event.comment.body == '/deploy-to-uat' && !github.event.repository.fork }}
    uses: ./.github/workflows/05_main_manual_deploy_to_uat.yml
    secrets:
      SFDX_UAT_URL: ${{ secrets.SFDX_UAT_URL }}
      UAT_ORG_USERNAME: ${{ secrets.UAT_ORG_USERNAME }}
      INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
      PROFILE_NAMES: ${{ secrets.PROFILE_NAMES }}
